@MindSpace.API_HostAddress = https://localhost:7096
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo0MDAwIiwiaXNzIjoicmVzdGF1cmFudHMiLCJleHAiOjE3NDA4OTE4MDUsInN1YiI6IjEiLCJlbWFpbCI6InN0dWRlbnQxQGV4YW1wbGUuY29tIiwiaWF0IjoxNzM4NzMxODA1LCJuYmYiOjE3Mzg3MzE4MDV9.WpZ6mMPSDyQVBhHnKqBc1BzPN58z6zW4EBphAguhncU

 
 
POST {{MindSpace.API_HostAddress}}/api/identity/register 
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "Password1!"
}

###
POST {{MindSpace.API_HostAddress}}/api/identities/login
Content-Type: application/json

{
  "email": "student1@example.com",
  "password": "Password1!"
}

###
GET {{MindSpace.API_HostAddress}}/api/test
Authorization: Bearer {{token}}
###

@id=1
GET {{MindSpace.API_HostAddress}}/api/test/{{id}}
Authorization: Bearer {{token}}

###

GET {{MindSpace.API_HostAddress}}/api/v1/Test
Authorization: Bearer {{token}}

###
